### ISSUE TITLE
Issue with commission

### ISSUE THREAD

**Issue by RepairDeskPOS** [Repair-DeskPOS/RepairDesk-Bugs#145]
There seems to be an issue when you add accessories from the ticket menu instead of pos that it doesn't give commission can you have them fix this as well?

Customer - Jeff (The smartphone medics)

**Comment by Repair-Desk** [comment]
@HafizAnas can you check this one please?

**Comment by Repair-Desk** [comment]
There seems to be a problem with commission. It seems to work properly when you ring up an accessory directly from POS

But if you add accessory to a ticket before or after creating the ticket it doesn't show in commission. Seems like the act of creating a ticket takes away the commission.

It seems to be putting the commission under my name instead of the employee maybe.

@HafizAnas can you check above scenario please?

**Comment by Repair-Desk** [comment]
@HafizAnas can you check this one once you get a chance?

**Comment by HafizAnas** [comment]
@RepairDeskPOS 
Your reported issue has been fixed.
