### ISSUE TITLE
Stock report shows things that have not reached stock warning

### ISSUE THREAD

**Issue by jeffsand8243** [Repair-DeskPOS/RepairDesk-Bugs#148]
Please make the stock report only show items that need to be ordered and have reached the stock warning level or below not just things that are not fully stocked

**Comment by Repair-Desk** [comment]
@jeffsand8243 The low stock report lists all products which are low on inventory based on minimum stock level defined against each product. 

If current on hand inventory is above the product minimum level or the product has no minimum stock level set, it will not be displayed on the low stock report.

 A **reorder level** indicates that the item must be purchased where as to prevent outages **"stock warning"** display items that are approaching the reorder point. 

It show items that don't need to be ordered, but are getting close because you may want to order before it reaches that point.

**Comment by jeffsand8243** [comment]
Hi. It seems like this is backwards to me and I have seen that other users think the same as me. That the reorder level should be the total amount you want to have in stock and the stock warning should show red when an item is at or below the warning level. But that is just my opinion. 

Thanks,
Jeff Sandridge
The Smartphone Medics
256-414-1199
www.TheSmartphoneMedics.com
7449 Highway 72 W. Suite D Madison, AL 35758


Locations

Madison (main location) - 
7449 Hwy 72 between Nance Rd. and Jeff rd. across from the new Hobby Lobby (next to Valley pools and Whiskers barber shop) suite D

(Hours) 10-6pm weekdays, 
10-3pm Saturday. Closed Sunday 


Huntsville (drop off location) - 
Jordan Ln. and Holmes Ave.  (inside Boost Mobile)
(Hours) 11-7pm Monday- Saturday
