### ISSUE TITLE
Calendar booking widget mobile. Number not working

### ISSUE THREAD

**Issue by andrewg1639** [Repair-DeskPOS/RepairDesk-Bugs#231]
When booking a repair through the calendar widget app, if a customer leaves their mobile phone number it is not currently coming through on the lead.
Instead it comes through as {customer_phone} on the email notification and when you check the lead in RD it is blank.
This has only happeded within the last week and we haven't changed anything from our end.

Here's where our widget is located

http://pimpmygadget.com.au/phone-and-tablet-repairs-brisbane/instant-quote

**Comment by Uzair-RepairDesk** [comment]
Hi @andrewg1639 
Andrew, We have fixed this issue yesterday. If customer enters phone number, system considers it Mobile number of the customer and it comes under Mobile field into the lead. 
We have also added a check "Pick phone number in any format" in configuration of "Appointment Calendar Widget" that will allow customer to enter mobile (phone) number in any format rather than restriction of a country code. Please find screenshot attached. 

If you want to test this at your end, please use new email address and phone number to book the repair order from widget. If you use existing details like email / mobile number, system takes details from existing customer record in lead. 

Please review at your end and if you have any other question, please feel free to ask. Thanks

I hope it helps. 

Regards,
Uzair

![pick phone number in any format](https://cloud.githubusercontent.com/assets/22955861/23994712/0839174c-0a68-11e7-97c6-0d7b8209c96e.png)

**Comment by andrewg1639** [comment]
Thanks Uzair
Looks like it works great.

 
     Kind Regards
     Andrew Gardiner | Pimp my Gadget | Manager
 
Brisbane Airport DFO : 07 3114 1177 – Shop 206 DFO Shopping centre, Ninth Ave, Brisbane Airport
Jindalee DFO : 07 3114 1177 – Shop 73 DFO Shopping centre, 16 Amazons place, Jindalee
Wholesale inquiries : 1300 790 430
   
***Disclaimer
This email and any attachments transmitted with it may contain information that is confidential, legally privileged or both and is intended solely for the use of the individual(s) or entity to whom it is addressed. No confidentiality or privilege is waived or lost by any mis-transmission. If you are not a named addressee, you should not disseminate, distribute or copy this email or its attachments. Please notify the sender immediately by email if you have received this email by mistake and delete this email and its attachments from your system. If you are not the intended recipient you are notified that disclosing, copying, distributing or taking any action in reliance on the information contained within this email is strictly prohibited. Any views expressed in this email are those of the individual sender except where the sender expressly, and with authority, states them to be the views of Pimp my Gadget. Warning: Although Pimp my Gadget has taken reasonable precautions to ensure no viruses are present in this email or its attachments, the company cannot and does not accept responsibility for any loss or damage arising from the use of this email or its attachments.
