### ISSUE TITLE
Form Integration

### ISSUE THREAD

**Issue by TPRS** [Repair-DeskPOS/RepairDesk-Bugs#280]
Heyo gang,

So we get online leads in two ways. First is calls which we can track using tracking software. The other is from people filling out forms on our website. Can we set up an API so we can automatically add those to our leads? And while at it, can we make sure we get notifications as soon as we get leads?

^^^^ This ^^^^ would be awesome!

**Comment by Repair-Desk** [comment]
@TPRS We already have appointment booking widget that allows your customers to book repair appointments. Furthermore you can also update the settings so that whenever a lead is received it display a pop up notification and play a sound alert as well.

More information on appointment booking widget is available here: https://repairdesk.uservoice.com/knowledgebase/articles/791394-how-to-set-up-appointment-calendar-widget

And I hope that if there’s anything else I can do for you, you won’t hesitate to let me know.

Thanks for helping us make this a platform you'll depend on.
