### ISSUE TITLE
Google Chrome not secure only when connecting to Cayan Terminal

### ISSUE THREAD

**Issue by icerepaircenter** [Repair-DeskPOS/RepairDesk-Bugs#352]
When using Google Chrome browser, the https browser tab stays secure until it has to communicate with the Cayan Genius Terminal. Then browser tab stays unsecure until you close the tab and re log back into Repairdesk.

**Comment by Repair-Desk** [comment]
**Hello @icerepaircenter,** 

We've reached out to Cayan and please find their response below:

Typically the unsecure connection is caused by the appropriate SSL certificate not being installed on the workstation. Can you please confirm that the Cayan SSL certificate is installed for this location? If this is a Windows workstation, you can confirm that by checking under the Trusted Root Certification Authorities>Certificates section of the cert manager as shown in the screenshot below:

![unnamed 1](https://user-images.githubusercontent.com/21986026/42020333-08f7e7f0-7ad1-11e8-9a17-8fddbafea365.jpg)

For further assistance please email: **partnerconcierge@cayan.com**

**Comment by icerepaircenter** [comment]
This seems to have resolved the issue. Thank you!
