### ISSUE TITLE
Woocommerce Category Error

### ISSUE THREAD

**Issue by zoombiefone** [Repair-DeskPOS/RepairDesk-Bugs#360]
Hi,
 There's a problem with the way the category within woocommerce is being mapped. Your system does not differentiate between main category and sub-category.

 In woocommerce, I would have a category called "Accessories" then a sub-category called "Screen protector" and another sub-category called "cases". Your integration pick up the category from woocommerce but it doesn't know which is a sub-category and which is the main category. It thinks accessories, screen protector and cases are all category in their own right.

 The problem with this is that when I try sync a product, even though they have the same SKU number, your system thinks that product doesn't exist because it doesn't match up with the category so it create another product in woocommerce.

**Comment by Repair-Desk** [comment]
**Hello @zoombiefone,**

Happy to help with this.

Currently RepairDesk inventory module doesn't allow you to create a sub-category and that's why the conflict happens however if a product has same SKU it should not allow you to create new product on WooCommerce.

Is it possible if you can reach us through live chat so we can assist you further regarding the same.

And I hope that if there’s anything else I can do for you, you won’t hesitate to let me know.

Dedicated to your retail success.

Usman
